/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_fabricmc_installer_launcher_MojangLauncherHelper */

#ifndef _Included_net_fabricmc_installer_launcher_MojangLauncherHelper
#define _Included_net_fabricmc_installer_launcher_MojangLauncherHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_fabricmc_installer_launcher_MojangLauncherHelper
 * Method:    isMojangLauncherOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_fabricmc_installer_launcher_MojangLauncherHelper_isMojangLauncherOpen
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
