name: Build
on: [push, pull_request]
jobs:
  unix:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-11.0, ubuntu-20.04]
        include:
          - runner: macos-11.0
            artifact: "*.dylib"
          - runner: ubuntu-20.04
            artifact: "*.so"
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - run: cmake -DCMAKE_BUILD_TYPE=Release -G Ninja
      - run: ninja
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.runner}} Artifacts
          path: ${{matrix.artifact}}

  windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [ Win32, x64, ARM, ARM64 ]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A ${{matrix.arch}}
      - run: msbuild fabric_installer_native_lib.sln /property:Configuration=Release
      - uses: actions/upload-artifact@v2
        with:
          name: Windows (${{matrix.arch}}) Artifacts
          path: "Release/*"