name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-2019, macos-11.0, ubuntu-20.04]
        include:
          - runner: windows-2019
            ninjaInstall: choco install ninja
          - runner: macos-11.0
            ninjaInstall: brew install ninja
          - runner: ubuntu-20.04
            ninjaInstall: apt-get update -y && apt-get install -y ninja-build
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v2
      - run: ${{matrix.ninjaInstall}}
      - run: cmake -DCMAKE_BUILD_TYPE=Release -G Ninja
      - run: ninja